# Generated by Django 5.1.3 on 2024-11-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_rename_completed_task_concluida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='relato',
            field=models.TextField(blank=True),
        ),
    ]
